"""recurso ganha tipo

Revision ID: 0d2bacd9919e
Revises: 92b6a0b6e69f
Create Date: 2026-07-13 01:48:05.431977

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0d2bacd9919e"
down_revision: Union[str, Sequence[str], None] = "92b6a0b6e69f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resources", sa.Column("tipo", sa.String(), server_default="quadra", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resources", "tipo")
    # ### end Alembic commands ###
