"""indice de reservas por recurso e inicio

Revision ID: 735b317a52e9
Revises: 12388da2dbe5
Create Date: 2026-10-04 01:02:18.056450

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "735b317a52e9"
down_revision: Union[str, Sequence[str], None] = "12388da2dbe5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_bookings_resource_id_starts_at", "bookings", ["resource_id", "starts_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_bookings_resource_id_starts_at", table_name="bookings")
    # ### end Alembic commands ###
